# automerge.yml
name: Auto Merge on Label

on:
  pull_request_target:
    types: [labeled]

jobs:
  merge:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge PR
        uses: pascalgn/automerge-action@v0.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
