name: Add Issue to Project Test

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to User Project #1
        uses: actions/add-to-project@main
        with:
          project-url: https://github.com/users/mbsaharan/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
